<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Professionnals extends \App\Entity\Professionnals implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Expertises' => [parent::class, 'Expertises', null],
        "\0".parent::class."\0".'Username' => [parent::class, 'Username', null],
        "\0".parent::class."\0".'adress' => [parent::class, 'adress', null],
        "\0".parent::class."\0".'appointment' => [parent::class, 'appointment', null],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'phone_number' => [parent::class, 'phone_number', null],
        "\0".parent::class."\0".'postalCode' => [parent::class, 'postalCode', null],
        "\0".parent::class."\0".'resetToken' => [parent::class, 'resetToken', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'speciality' => [parent::class, 'speciality', null],
        'Expertises' => [parent::class, 'Expertises', null],
        'Username' => [parent::class, 'Username', null],
        'adress' => [parent::class, 'adress', null],
        'appointment' => [parent::class, 'appointment', null],
        'city' => [parent::class, 'city', null],
        'confirm_password' => [parent::class, 'confirm_password', null],
        'email' => [parent::class, 'email', null],
        'firstname' => [parent::class, 'firstname', null],
        'id' => [parent::class, 'id', null],
        'lastname' => [parent::class, 'lastname', null],
        'password' => [parent::class, 'password', null],
        'phone_number' => [parent::class, 'phone_number', null],
        'postalCode' => [parent::class, 'postalCode', null],
        'resetToken' => [parent::class, 'resetToken', null],
        'roles' => [parent::class, 'roles', null],
        'speciality' => [parent::class, 'speciality', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
            'confirm_password' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
