<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Aviability extends \App\Entity\Aviability implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'aviabilityPro' => [parent::class, 'aviabilityPro', null],
        "\0".parent::class."\0".'durationDate' => [parent::class, 'durationDate', null],
        "\0".parent::class."\0".'endDate' => [parent::class, 'endDate', null],
        "\0".parent::class."\0".'endTime' => [parent::class, 'endTime', null],
        "\0".parent::class."\0".'gapDate' => [parent::class, 'gapDate', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'startDate' => [parent::class, 'startDate', null],
        "\0".parent::class."\0".'startTime' => [parent::class, 'startTime', null],
        'aviabilityPro' => [parent::class, 'aviabilityPro', null],
        'durationDate' => [parent::class, 'durationDate', null],
        'endDate' => [parent::class, 'endDate', null],
        'endTime' => [parent::class, 'endTime', null],
        'gapDate' => [parent::class, 'gapDate', null],
        'id' => [parent::class, 'id', null],
        'startDate' => [parent::class, 'startDate', null],
        'startTime' => [parent::class, 'startTime', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
