<?php

namespace ContainerDDXHjNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_73M6G4IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.73M6G4I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.73M6G4I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appointmentRepository' => ['privates', 'App\\Repository\\AppointmentRepository', 'getAppointmentRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'appointmentRepository' => 'App\\Repository\\AppointmentRepository',
            'manager' => '?',
        ]);
    }
}
