<?php

namespace ContainerDDXHjNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FgbOLE6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fgbOLE6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fgbOLE6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hashPass' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'patientUser' => ['privates', 'App\\Repository\\PatientsRepository', 'getPatientsRepositoryService', true],
            'proUser' => ['privates', 'App\\Repository\\ProfessionnalsRepository', 'getProfessionnalsRepositoryService', true],
        ], [
            'hashPass' => '?',
            'manager' => '?',
            'patientUser' => 'App\\Repository\\PatientsRepository',
            'proUser' => 'App\\Repository\\ProfessionnalsRepository',
        ]);
    }
}
