<?php

namespace ContainerDDXHjNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CPHlA71Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CPHlA71' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CPHlA71'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'professionnal' => ['privates', 'App\\Repository\\ProfessionnalsRepository', 'getProfessionnalsRepositoryService', true],
            'repoSpecialities' => ['privates', 'App\\Repository\\SpecialitiesRepository', 'getSpecialitiesRepositoryService', true],
        ], [
            'professionnal' => 'App\\Repository\\ProfessionnalsRepository',
            'repoSpecialities' => 'App\\Repository\\SpecialitiesRepository',
        ]);
    }
}
