<?php

namespace App\DataFixtures;

use App\Entity\Expertises as EntityExpertises;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class Expertises extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $expertises = [
            'Vaccination COVID-19',
            'Dépistage COVID-19 test PCR (prélèvement naso-pharyngé)',
            'Dépistage COVID-19 test antigénique (prélèvement naso-pharyngé)',
            'Dépistage COVID-19 autotest supervisé par un professionnel de santé',
            'Abcès dentaire',
            'Accident vasculaire cérébral (AVC)',
            'Accompagnement haptonomique périnatal',
            'Accompagnement interruption volontaire de grossesse (IVG)',
            'Accouchement',
            'Accouchement physiologique',
            'Acné',
            'Acouphènes',
            'Activité Physique Adaptée (APA)',
            'Activité Physique Adaptée - Cancer du sein',
            'Addiction',
            'Adénome de la prostate',
            'Aide aux aidants',
            'Alcoologie',
            'Alignement dentaire invisible',
            'Alimentation de la femme enceinte',
            'Allaitement',
            'Allergie',
            'Allergie alimentaire',
            'Allergie aux médicaments',
            'Allergie aux venins',
            'Allergie cutanée',
            'Allergie pollens',
            'Allergie respiratoire',
            'Allergologue pédiatrique',
            'Allergologue-pneumo-pédiatre',
            'Amblyopie',
            'Amélogenèse imparfaite',
            'Amniocentèse',
            'Analyse médicale',
            'Anesthésie pédiatrique',
            'Anévrisme',
            'Anévrisme cérébral',
            'Angiœdème',
            'Angiographie',
            'Angiome',
            'Angioplastie',
            'Angioscanner',
            'Anneau gastrique',
            'Anomalie du développement structurel des dents',
            'Apnée du sommeil',
            'Apnée du sommeil de l \'enfant',
            'Appareil dentaire',
            'Approche psychosomatique',
            'Artériographie',
            'Artérite',
            'Arthrite',
            'Arthroscanner',
            'Arthroscopie',
            'Arthroscopie de la hanche',
            'Arthroscopie de l\'épaule',
            'Arthroscopie du genou',
            'Arthrose',
            'Arythmie',
            'Assistance médicale à la procréation',
            'Asthmologie',
            'Astigmatisme',
            'Attelle',
            'Attelle de doigt',
            'Attelle de main',
            'Attelle de poignet',
            'Audiogramme',
            'Audiométrie',
            'Audiophonologie',
            'Augmentation mammaire',
            'Auriculothérapie',
            'Autisme',
            'Autotest VIH',
            'Auxiliaire médical en pratique avancée',
            'Ballon gastrique',
            'Balnéothérapie',
            'Bas de contention',
            'Bébé vision',
            'Bilan cognitif',
            'Bilan d\'assurance',
            'Bilan de compétences',
            'Bilan de la vue',
            'Bilan de santé',
            'Bilan gériatrique',
            'Bilan M\'T Dents',
            'Bilan orthophonique',
            'Bilan orthoptique',
            'Bilan podologique',
            'Bilan postural',
            'Bilan psychomoteur',
            'Bilan urodynamique',
            'Biokinergie',
            'Biologie génétique',
            'Biologiste de la reproduction',
            'Biomicroscopie ultrasonore (UBM)',
            'Biopsie',
            'Biopsie mammaire',
            'Biopsie testiculaire',
            'Biothérapies',
            'Blanchiment des dents',
            'Blépharoplastie',
            'Body lift',
            'Bruxisme',
            'Burn out',
            'Bypass',
            'Calculs rénaux',
            'Canal carpien',
            'Canal lombaire étroit',
            'Cancer anal',
            'Cancer de la prostate',
            'Cancer de la vessie',
            'Cancer de la vulve',
            'Cancer de l\'estomac',
            'Cancer de l\'œsophage',
            'Cancer de l\'utérus',
            'Cancer du col de l\'utérus',
            'Cancer du côlon',
            'Cancer du foie',
            'Cancer du poumon',
            'Cancer du rectum',
            'Cancer du rein',
            'Cancer du sein',
            'Cancer du vagin',
            'Cancérologie digestive',
            'Cancérologie du sein',
            'Cancérologie thoracique',
            'Cancérologie urologique',
            'Cancérologue gynécologue',
            'Candidose',
            'Capillaroscopie',
            'Carcinome hépatocellulaire',
            'Cardiologie fœtale',
            'Cardiologie hémodynamique',
            'Cardiologue du sport',
            'Cardiologue interventionnel',
            'Cardiologue rythmologue',
            'Cardiopédiatre',
            'Carie',
            'Carnet jaune',
            'Caryotype',
            'Casque pour bébé',
            'Cataracte',
            'Ceinture lombaire',
            'Centre de ressource paramédicale (CRPM)',
            'Céphalée et migraine',
            'Céphalée et migraine de l\'enfant',
            'Certificat de plongée',
            'Certificat de vaccination international',
            'Cervicalgie',
            'Chaîne musculaire G.D.S',
            'Chalazion',
            'Champ visuel',
            'Chaussures orthopédiques',
            'Chimiothérapie',
            'Chirurgie ambulatoire',
            'Chirurgie bariatrique',
            'Chirurgie buccale',
            'Chirurgie de la cataracte',
            'Chirurgie de la myopie',
            'Chirurgie de l\'épaule, de la cheville et du pied',
            'Chirurgie des brûlés pédiatrique',
            'Chirurgie du pancréas',
            'Chirurgie endocrinienne et métabolique',
            'Chirurgie esthétique et réparation du sein',
            'Chirurgie et cancérologie du sein',
            'Chirurgie gynécologique et urologique',
            'Chirurgie mammaire',
            'Chirurgien artériel et veineux',
            'Chirurgien arthroscopique',
            'Chirurgien cardiaque',
            'Chirurgien cardiaque pédiatrique',
            'Chirurgien cardio-vasculaire',
            'Chirurgien crânien et cérébral',
            'Chirurgien crânio-facial',
            'Chirurgien de la carotide',
            'Chirurgien de la cheville',
            'Chirurgien de la cheville percutanée',
            'Chirurgien de la colonne vertébrale et de la moelle épinière',
            'Chirurgien de la cornée',
            'Chirurgien de l\'adénome prostatique',
            'Chirurgien de la hanche',
            'Chirurgien de la hanche, du genou et du pied',
            'Chirurgien de la lithiase urinaire',
            'Chirurgien de la paroi abdominale',
            'Chirurgien de la presbytie',
            'Chirurgien de la prostate',
            'Chirurgien de la réfraction',
            'Chirurgien de la rétine',
            'Chirurgien de la scoliose',
            'Chirurgien de la stérilité',
            'Chirurgien de l\'astigmatisme',
            'Chirurgien de la thyroïde',
            'Chirurgien de la vulve',
            'Chirurgien de l\'épaule',
            'Chirurgien de l\'hallux valgus',
            'Chirurgien de l\'hypermétropie',
            'Chirurgien de l\'incontinence urinaire',
            'Chirurgien de l\'infertilité',
            'Chirurgien de l\'obésité',
            'Chirurgien de l\’œsophage et de l\'estomac',
            'Chirurgien de l\'oreille',
            'Chirurgien dermatologique',
            'Chirurgien dermatologique cervico-facial',
            'Chirurgien des brûlés',
            'Chirurgien des calculs urinaires',
            'Chirurgien des cancers avec technique coelioscopique et robotique',
            'Chirurgien des dents de sagesse',
            'Chirurgien des gencives',
            'Chirurgien des glandes salivaires',
            'Chirurgien des ligaments croisés',
            'Chirurgien des membres inférieurs',
            'Chirurgien des membres supérieurs',
            'Chirurgien des paupières',
            'Chirurgien des sinus',
            'Chirurgien des testicules',
            'Chirurgien des tumeurs cutanées de la face et du cou',
            'Chirurgien des varices',
            'Chirurgien des voies biliaires',
            'Chirurgien des voies lacrymales',
            'Chirurgien digestif',
            'Chirurgien digestif et de l’obésité',
            'Chirurgien du coude',
            'Chirurgien du dos',
            'Chirurgien du foie',
            'Chirurgien du genou',
            'Chirurgien du genou et de la hanche',
            'Chirurgien du glaucome',
            'Chirurgien du membre supérieur',
            'Chirurgien du périnée',
            'Chirurgien du pied',
            'Chirurgien du pied et de la cheville',
            'Chirurgien du plexus brachial',
            'Chirurgien du poignet',
            'Chirurgien du prolapsus génital et de l\'incontinence urinaire de la femme',
            'Chirurgien du rachis',
            'Chirurgien du rectum',
            'Chirurgien du sein',
            'Chirurgien du sport',
            'Chirurgien du strabisme',
            'Chirurgien du visage',
            'Chirurgien endonasal',
            'Chirurgien endovasculaire',
            'Chirurgien esthétique',
            'Chirurgien gynécologue',
            'Chirurgien gynécologue esthétique',
            'Chirurgien gynécologue et obstétrique',
            'Chirurgien gynécologue et uro-gynécologue',
            'Chirurgien hépato-biliaire',
            'Chirurgien herniaire',
            'Chirurgien maxillo-facial pédiatrique',
            'Chirurgien oculoplastique',
            'Chirurgien ophtalmologue',
            'Chirurgien orthognathique',
            'Chirurgien orthopédiste pédiatrique',
            'Chirurgien pariétal',
            'Chirurgien pédiatrique',
            'Chirurgien pelvien',
            'Chirurgien plasticien',
            'Chirurgien plasticien et esthétique pédiatrique',
            'Chirurgien plasticien pédiatrique',
            'Chirurgien plastique et esthétique de la face et du cou',
            'Chirurgien pré-implantaire',
            'Chirurgien proctologique',
            'Chirurgien prothétique',
            'Chirurgien sénologue',
            'Chirurgien thoracique',
            'Chirurgien thoracique et vasculaire',
            'Chirurgien thoracique pédiatrique',
            'Chirurgien urologue andrologue',
            'Chirurgien vaginal',
            'Chirurgien viscéral pédiatrique',
            'Chirurgie orale pédiatrique',
            'Chirurgie orthopédique pédiatrique',
            'Chirurgie plastique et gynécologique',
            'Chirurgie reconstructrice',
            'Chirurgie réparatrice',
            'Chirurgie robotique',
            'Chirurgie urologique et sexologie',
            'Chirurgie urologique pédiatrique',
            'Chlamydia',
            'Cholestéatome',
            'Cholestérol',
            'Cimentoplastie',
            'Circoncision',
            'Coach en développement personnel',
            'Coach en développement professionnel',
            'Coelioscopie',
            'Coloscanner',
            'Coloscopie',
            'Colposcopie',
            'Condylome',
            'Cône beam',
            'Conisation',
            'Conjonctivite',
            'Conseil en diététique',
            'Conseil en nutrition',
            'Conseil en soins de la peau',
            'Conseiller conjugal et familial',
            'Contraception',
            'Contraception définitive',
            'Contrôle de la réfraction visuelle',
            'Coronarographie',
            'Coroscanner',
            'Corset',
            'Couperose',
            'Couronne dentaire',
            'Covid long',
            'Cryolipolyse',
            'Cryothérapie',
            'Cryothérapie corps entier (CCE)',
            'Curiethérapie',
            'Cytoponction',
            'Daltonisme',
            'Décodage biologique',
            'Dentiste pédiatrique',
            'Dentisterie numérique',
            'Dépistage',
            'Dépistage COVID-19 test sérologique (prise de sang)',
            'Dépistage de papillomavirus humain (HPV)',
            'Dépistage infection urinaire',
            'Dépistage variole du singe',
            'Dermatologie buccale',
            'Dermatologie chirurgicale',
            'Dermatologue allergologue',
            'Dermatologue esthétique',
            'Dermatologue lasériste',
            'Dermatologue médical',
            'Dermatologue pédiatrique',
            'Dermite séborrhéique',
            'Dermographie',
            'Dermographie médicale et esthétique',
            'Dermopigmentation',
            'Détartrage',
            'Détatouage au laser',
            'Dévitalisation',
            'Diabète',
            'Diabète gestationnel',
            'Diabète type 1',
            'Diabète type 2',
            'Diabétologie pédiatrique',
            'Diabétologue',
            'Diagnostic prénatal',
            'Dialyse',
            'Diététique énergétique',
            'Diététique pédiatrique',
            'Dissection aortique',
            'DLCO',
            'DMLA (Dégénérescence Maculaire Liée à l\'Âge)',
            'Doigts à ressaut',
            'Don de sperme',
            'Don d\'ovocytes',
            'Doppler',
            'Drainage',
            'Drainage lymphatique',
            'Drépanocytose',
            'Dry needling',
            'Dysfonctionnement temporo-mandibulaire (DTM)',
            'Dyslipidémie',
            'Échodoppler',
            'Échodoppler vasculaire',
            'Écho-endoscopie digestive',
            'Échographie',
            'Échographie 3D',
            'Échographie abdominale',
            'Échographie cardiaque',
            'Échographie cardiaque de stress (effort et autre)',
            'Échographie cardiaque fœtale',
            'Échographie de datation',
            'Échographie de la thyroïde',
            'Échographie endo-anale',
            'Échographie gynécologique',
            'Échographie gynécologique et obstétricale',
            'Échographie mammaire',
            'Échographie musculo-squelettique',
            'Échographie obstétricale',
            'Échographie ostéo-articulaire',
            'Échographie pédiatrique',
            'Échographie pelvienne',
            'Échographie prostatique et testiculaire',
            'Échographie rénale',
            'Échographie transœsophagienne',
            'Échographie urinaire',
            'Eczéma',
            'Educateur de jeunes enfants',
            'Educateur spécialisé',
            'Éducation au diabète',
            'Éducation thérapeutique',
            'Électro-cardiogramme de l\'enfant',
            'Électrocardiogramme (ECG)',
            'Électro-encéphalographie (EEG)',
            'Électromyogramme (EMG)',
            'Électrothérapie',
            'Embolie pulmonaire',
            'Embolisation',
            'Embolisation de fibromes utérins',
            'Endermologie',
            'Endocrinologie gynécologique',
            'Endocrinologue pédiatrique',
            'Endodontiste',
            'Endométriose',
            'Endoprothèse',
            'Endoscopie',
            'Endoscopie bronchique interventionnelle',
            'Endoscopie digestive',
            'Endoscopie et laser ORL',
            'Endoscopie interventionnelle',
            'Enseignant spécialisé',
            'Entomologie médicale',
            'Entorse',
            'Entretien femme enceinte',
            'Entretien motivationnel',
            'Entretien prénatal précoce',
            'EOS',
            'Épilation électrique',
            'Épilation laser',
            'Épilepsie',
            'Épreuve d\'effort',
            'Épreuves fonctionnelles respiratoires (EFR)',
            'Eutonie',
            'Examen de prévention en santé',
            'Examens cardiologiques',
            'Examens neurologiques',
            'Expertise judiciaire',
            'Exploration cardiaque',
            'Exploration endoscopique et digestive',
            'Exploration fonctionnelle',
            'Exploration fonctionnelle neurologique',
            'Exploration fonctionnelle pédiatrique',
            'Exploration gynécologique et obstétricale',
            'Exploration neurologique',
            'Exploration ophtalmologique',
            'Exploration ORL',
            'Exploration pneumologique',
            'Exploration rénale',
            'Exploration urodynamique',
            'Extraction dentaire',
            'Extrasystoles',
            'Facette dentaire',
            'Fécondation In Vitro (FIV)',
            'Fibrome utérin',
            'Fibroscan',
            'Fibroscopie',
            'Fibroscopie bronchique',
            'Fibroscopie trachéobronchique',
            'Fissure anale',
            'Fistule artério-veineuse',
            'Fond d\'œil',
            'Freinectomie',
            'Frottis',
            'Gastro-entérologue',
            'Gastro-entérologue pédiatrique',
            'Gastroscopie',
            'Généticien pédiatrique',
            'Gérontologue',
            'Gérontopsychiatre',
            'Gestalt-thérapie',
            'Gingivite',
            'Glaucome',
            'Gouttière dentaire',
            'Grain de beauté',
            'Greffe capillaire',
            'Greffe de barbe',
            'Greffe de gencive',
            'Greffe de la cornée',
            'Greffe osseuse',
            'Grossesse pathologique',
            'Guidance parentale',
            'Gynécologie de l’adolescente',
            'Gynécologie pédiatrique',
            'Gynécologie sexologie',
            'HandiConsult',
            'Hématurie',
            'Hémorroïdes',
            'Hémostase',
            'Hépatite',
            'Hépatite virale',
            'Hépato-gastro-entérologue pédiatrique',
            'Hépatologie pédiatrique',
            'Hépatologue',
            'Hernie discale',
            'Hernie inguinale',
            'Holter ECG',
            'Holter tensionnel',
            'Hydrotomie percutanée',
            'Hyperactivité - Inhibition',
            'Hypercholestérolémie',
            'Hyperhidrose',
            'Hypermétropie',
            'Hypersomnie',
            'Hypertension artérielle',
            'Hypertrophie de la prostate',
            'Hypnose médicale',
            'Hystérectomie',
            'Hystérographie',
            'Hystéroscopie',
            'Hystérosonographie',
            'Immuno-allergologie',
            'Immuno-hématologie',
            'Immunologie et hématologie pédiatrique',
            'Immunologie pédiatrique',
            'Immunothérapie',
            'Implant cochléaire',
            'Implant contraceptif',
            'Implant dentaire',
            'Implant mammaire',
            'Implantologue',
            'Implantologue dentaire',
            'Incontinence anale',
            'Incontinence urinaire',
            'Infarctus du myocarde',
            'Infectiologie pédiatrique',
            'Infection urinaire',
            'Infertilité',
            'Infiltration',
            'Infiltration écho-guidée',
            'Infiltration radioguidée',
            'Infirmière Asalée',
            'Infirmière coordinatrice',
            'Injection',
            'Injection d\'acide hyaluronique',
            'Injection de plasma riche en plaquettes (PRP)',
            'Injection de toxine botulique',
            'Injection intravitréenne',
            'Insémination artificielle',
            'Insomnie',
            'Insuffisance cardiaque',
            'Insuffisance coronaire',
            'Insuffisance rénale',
            'Insuffisance respiratoire',
            'Interruption volontaire de grossesse (IVG) chirurgicale',
            'Interruption volontaire de grossesse (IVG) médicale et chirurgicale',
            'Interruption volontaire de grossesse (IVG) médicamenteuse',
            'Intolérance alimentaire',
            'Ionophorèse',
            'IRM',
            'IRM cardiaque',
            'IRM pédiatrique',
            'Jambes lourdes',
            'Kératocône',
            'Kinesio Taping',
            'Kinésithérapeute du sport',
            'Kinésithérapie de la femme enceinte',
            'Kinésithérapie esthétique',
            'Kinésithérapie pédiatrique',
            'Kinésithérapie respiratoire et cardio-vasculaire',
            'Kinésithérapie respiratoire et pédiatrique',
            'Kinésithérapie uro-gynécologique et ano-rectale',
            'Kit dépistage cancer colorectal',
            'K-Tape',
            'Kyphoplastie',
            'Laboratoire de biologie médicale',
            'Laser',
            'Laser ablatif',
            'Laser CO2',
            'Laser de la prostate',
            'Laser dentaire',
            'Laser dermatologique',
            'Laser esthétique',
            'Laser médical',
            'Laser ophtalmologique',
            'Laser thérapeutique',
            'Laser vaginal',
            'Laser vasculaire',
            'Lasik',
            'Lentilles de contact',
            'Lifting du visage',
            'Lifting mammaire',
            'Ligamentoplastie',
            'Lipoaspiration',
            'Lipofilling',
            'Lipofilling mammaire',
            'Liposuccion',
            'Lithotritie',
            'Location de matériel médical',
            'Lombalgie',
            'Lumière pulsée',
            'Luminothérapie',
            'Lunettes',
            'Lupus',
            'Luxopuncture',
            'Lymphologie',
            'Maladie auto-immune',
            'Maladie d’Alzheimer',
            'Maladie de Basedow',
            'Maladie de Crohn',
            'Maladie de Dupuytren',
            'Maladie de Lyme',
            'Maladie de Ménière',
            'Maladie de Parkinson',
            'Maladie de Verneuil (hidradénite suppurée)',
            'Maladie du sang',
            'Maladies/infections sexuellement transmissibles (MST/IST)',
            'Maladies inflammatoires chroniques de l\'intestin (MICI)',
            'Mammographie',
            'Manchon de compression',
            'Manométrie œsophagienne',
            'MAPA (Mesure Ambulatoire de la Pression Artérielle)',
            'Massage bébé',
            'Massage thérapeutique',
            'Masseur-kinésithérapeute du sport',
            'Masseur-kinésithérapeute ostéopathe',
            'Maternité',
            'Médecin aéronautique',
            'Médecin agréé',
            'Médecin agréé permis de conduire',
            'Médecin anti-âge',
            'Médecin-conseil',
            'Médecin de la nutrition pédiatrique',
            'Médecin de l\'enfant et de l\'adolescent',
            'Médecin de plongée',
            'Médecin du sommeil',
            'Médecin du sommeil pédiatrique',
            'Médecine des brûlés',
            'Médecine des maladies rares',
            'Médecine des voyages',
            'Médecine du handicap',
            'Médecine du surpoids et de l\'obésité',
            'Médecine du surpoids et de l\'obésité pédiatrique',
            'Médecine fœtale',
            'Médecine fonctionnelle et nutritionnelle',
            'Médecine hyperbare',
            'Médecine interne pédiatrique',
            'Médecin esthétique',
            'Médecine tropicale',
            'Médecin homéopathe',
            'Médecin ostéopathe',
            'Médecin plaies et cicatrisation',
            'Médecin préventif',
            'Médecin réanimateur pédiatrique',
            'Médecin sexologue',
            'Mélanome',
            'Ménopause',
            'MEOPA',
            'Mésothérapie',
            'Méthode Allyane',
            'Méthode Bonapace',
            'Méthode Busquet',
            'Méthode de Gasquet',
            'Méthode École du Dos',
            'Méthode McKenzie',
            'Méthode Mézières',
            'Méthode Poyet',
            'Microchirurgien des nerfs périphériques',
            'Microkinésithérapie',
            'Microneedling',
            'Micronutritionniste',
            'Mindfulness',
            'Moniteur éducateur',
            'Monitorage de l\'ovulation /Comptage Folliculaire',
            'Monitoring fœtal',
            'Monture',
            'Musicothérapeute',
            'Mycose',
            'Myopie',
            'Néphrologue pédiatrique',
            'Neurinome',
            'Neurochirurgie du rachis',
            'Neurochirurgien pédiatrique',
            'Neurofeedback',
            'Neuro-ophtalmologie',
            'Neuro-pédiatre',
            'Neurophysiologie',
            'Neurophysiologie pédiatrique',
            'Neuropsychologue',
            'Neuro-radiologue',
            'Neuro-radiologue interventionnel',
            'Neurostimulation électrique transcutanée (TENS)',
            'Neuro-urologie',
            'Névralgie',
            'Névralgie cervico-brachiale',
            'Névralgie faciale',
            'Névrome de Morton',
            'Nutrithérapie',
            'Nutrition du sportif',
            'Nutrition entérale',
            'Nutrition parentérale',
            'Nymphoplastie',
            'Obésité',
            'Obstétrique',
            'Occlusodontie',
            'OCT',
            'Odontologie chirurgicale',
            'Odontologie conservatrice',
            'Odontologie pédiatrique',
            'Œil de verre',
            'Onco-cardiologie',
            'Oncogériatrie',
            'Oncogériatrie',
            'Onco-hématologue pédiatrique',
            'Oncologie',
            'Oncologie thoracique',
            'Oncologue',
            'Onco-rhumatologue',
            'Ondes de choc',
            'Ongle incarné',
            'Ophtalmo-diabétologie',
            'Ophtalmologie esthétique',
            'Ophtalmologie médico-chirurgicale',
            'Ophtalmologue pédiatrique',
            'Orgelet',
            'Orientation scolaire',
            'ORL cancérologique',
            'ORL et chirurgien plastique',
            'ORL gériatrique',
            'ORL laryngologue',
            'ORL otologiste',
            'ORL pédiatrique',
            'ORL rhinologique',
            'Orthèse',
            'Orthèse d’avancée mandibulaire (OAM)',
            'Orthèse de coude',
            'Orthèse de poignet',
            'Orthèse de pouce',
            'Orthèse plantaire',
            'Orthodontie pédiatrique',
            'Orthodontie pour adulte',
            'Orthokératologie',
            'Orthonyxie',
            'Orthopédie dento-faciale',
            'Orthopédie dento-maxillo-faciale',
            'Orthopédie-orthèses-podologie',
            'Orthopédiste',
            'Orthoplastie',
            'Orthoptie pédiatrique',
            'Ortho-rhumatologie',
            'Ostéodensitométrie',
            'Ostéopathie aquatique',
            'Ostéopathie biodynamique',
            'Ostéopathie crânienne',
            'Ostéopathie de la femme enceinte',
            'Ostéopathie du sport',
            'Ostéopathie gynécologique',
            'Ostéopathie hémodynamique',
            'Ostéopathie maxillo-faciale et oro-faciale',
            'Ostéopathie myofasciale',
            'Ostéopathie pédiatrique',
            'Ostéopathie structurelle',
            'Ostéopathie viscérale',
            'Ostéoporose',
            'Otoplastie',
            'Otospongiose',
            'Paludisme',
            'Pansements et petites chirurgies',
            'Parasitologie',
            'Parodontie',
            'Parodontite',
            'Pédiatre néonatologue',
            'Pédiatrie hématologie',
            'Pédicurie',
            'Pédodontiste',
            'Pédopsychiatre',
            'Pédopsychologie',
            'Peeling',
            'Pelvi-périnéologie',
            'Pénoplastie',
            'Perfusion',
            'Pessaire',
            'Phlébectomie',
            'Phlébite',
            'pH-métrie',
            'Photothérapie dynamique',
            'Photothérapie et PUVAthérapie',
            'Physiothérapeute',
            'Phytothérapie',
            'PICC-line',
            'Pilule contraceptive',
            'Pilule du lendemain',
            'Planning familial',
            'Plastie abdominale',
            'Plastie mammaire',
            'PMA/AMP - FIV - Fertilité',
            'Pneumo-allergologue',
            'Pneumo-hématologie',
            'Pneumo-pédiatre',
            'PNL (Programmation Neuro-Linguistique)',
            'Podologie',
            'Podologie du sport',
            'Polyarthrite',
            'Polygraphie',
            'Polygraphie ventilatoire',
            'Polysomnographie',
            'Pompe à insuline',
            'Pontage',
            'Portage bébé',
            'Pose de stent',
            'Pose de stérilet',
            'Posturologie',
            'PPR (pseudo polyarthrite rhizomélique)',
            'PRADO (Programme d\'accompagnement au retour à domicile)',
            'Pratique esthétique',
            'Prélèvement vaginal',
            'Préparation à la naissance',
            'Presbylasik',
            'Préservation de la fertilité',
            'Pressothérapie',
            'Prévention cardio-vasculaire',
            'Prise de sang',
            'Prise en charge thérapeutique du Syndrome d\'Ehlers Danlos (SED)',
            'Proctologie médicale',
            'Proctologue',
            'Prolapsus ou descente d\'organe',
            'Prophylaxie',
            'Prophylaxie pré-exposition (PrEP)',
            'Protection Maternelle et Infantile (PMI)',
            'Protéinurie',
            'Prothèse',
            'Prothèse auditive',
            'Prothèse capillaire',
            'Prothèse de doigt',
            'Prothèse dentaire fixe ou amovible',
            'Prothèse d\'épaule',
            'Prothèse de poignet',
            'Prothèse du genou',
            'Prothèse mammaire externe',
            'Prothèse maxillo-faciale',
            'Prothèse oculaire',
            'Prothèse sur implant',
            'Prothèse totale de hanche',
            'Psoriasis',
            'Psychiatrie de l\'adolescent',
            'Psychiatrie polyvalente',
            'Psychocriminologie',
            'Psychogénéalogie',
            'Psychologie de l\'adolescent',
            'Psychologie de l\'enfant',
            'Psychologie du sport',
            'Psychologie pédiatrique',
            'Psychologie positive',
            'Psychologue clinicien',
            'Psychologue du travail',
            'Psycho-oncologie',
            'Psychopathologie du travail',
            'Psychopédagogie',
            'Psychotraumatologie',
            'Puéricultrice',
            'Purpura Thrombopénique Immunologique (PTI)',
            'Radiofréquence',
            'Radiographie',
            'Radiographie dentaire',
            'Radiologie vasculaire',
            'Radiologue interventionnel',
            'Radiologue pédiatrique',
            'Radio panoramique',
            'Radio-pédiatre',
            'Réanimation chirurgicale',
            'Réathlétisation musculaire',
            'Récession gingivale',
            'Reconstruction mammaire',
            'Rectoscopie',
            'Réduction mammaire',
            'Rééducation abdominale',
            'Rééducation abdominale hypopressive',
            'Rééducation après cancer du rein',
            'Rééducation après cancer du sein',
            'Rééducation de la déglutition',
            'Rééducation de la main',
            'Rééducation de l\'épaule',
            'Rééducation des patients Alzheimer',
            'Rééducation du dos',
            'Rééducation du membre inférieur',
            'Rééducation du membre supérieur',
            'Rééducation du périnée',
            'Rééducation du pied post-opératoire',
            'Rééducation fonctionnelle',
            'Rééducation neurologique',
            'Rééducation oro-faciale ou maxillo-faciale',
            'Rééducation orthophonique',
            'Rééducation périnéale masculine',
            'Rééducation post-COVID',
            'Rééducation uro-gynécologique',
            'Rééducation vestibulaire',
            'Rééquilibrage alimentaire',
            'Réhabilitation respiratoire',
            'Remédiation cognitive',
            'Résonance Énergétique par Stimulation Cutanée (RESC)',
            'Rhinoplastie',
            'Rhizarthrose',
            'Rhumatisme inflammatoire',
            'Rhumatologie interventionnelle',
            'Rhumatologue pédiatrique',
            'Ronflements',
            'Rosacée',
            'Rythmologie',
            'Rythmologue interventionnel',
            'Saignée',
            'Saignement des gencives',
            'Scanner',
            'Scanner coronaire',
            'Scarlatine',
            'Schizophrénie',
            'Sciatique',
            'Scintigraphie',
            'Scintigraphie cardiaque',
            'Scintigraphie myocardique',
            'Scintigraphie osseuse',
            'Scintigraphie pulmonaire',
            'Scintigraphie thyroïdienne',
            'Sclérose',
            'Sclérose en plaques (SEP)',
            'Sclérothérapie des varices',
            'Sécheresse oculaire',
            'Semelles orthopédiques',
            'Semelles orthopédiques 3D',
            'Sénologue',
            'Septoplastie',
            'Sevrage tabagique',
            'Sexologue',
            'Sleeve',
            'Soin des gencives',
            'Soin de support oncologique',
            'Souffrance au travail',
            'Spécialiste en médecine physique et de réadaptation pédiatrique',
            'Spécialiste en médecine traditionnelle chinoise',
            'Spécialiste en périnatalité',
            'Spermoculture',
            'Spermogramme',
            'Spirométrie',
            'Spondylarthrite',
            'Spondylolisthésis',
            'Stellite dentaire',
            'Stérilité',
            'Stimulation cardiaque',
            'Stimulation magnétique transcrânienne (rTMS)',
            'Stomathérapie',
            'Stomatologie pédiatrique',
            'Strabologie',
            'Suite de soins',
            'Suivi de grossesse',
            'Suivi des patients transgenres',
            'Suivi du sportif',
            'Suivi en gynécologie',
            'Suivi ophtalmologique',
            'Surdité',
            'Surfaçage',
            'Surpoids',
            'Symptothermie',
            'Syndrome d\'Ehlers-Danlos (SED)',
            'Syndrome du défilé thoraco-brachial',
            'Syndrome inflammatoire',
            'Syndrome néphrotique',
            'Tabacologue',
            'Tassement vertébral',
            'TDA/TDAH (trouble du déficit d\'attention avec/sans hyperactivité)',
            'Técarthérapie',
            'Technique des ventouses',
            'Technique linguale',
            'Teigne',
            'Tendinite',
            'TEP scan',
            'Test combiné Covid + Grippe',
            'Test de personnalité',
            'Test de QI (Quotient Intellectuel)',
            'Test isocinétique',
            'Test psychotechnique',
            'Test Rapide d’Orientation Diagnostique (TROD) pour angine',
            'Thérapeute d\'orientation psychanalytique',
            'Thérapie analytique',
            'Thérapie cognitive et comportementale (TCC)',
            'Thérapie d\'acceptation et d\'engagement (ACT)',
            'Thérapie EMDR',
            'Thérapie familiale',
            'Thérapie humaniste',
            'Thérapie ICV (Intégration du Cycle de la Vie)',
            'Thérapie manuelle',
            'Thérapie manuelle orthopédique',
            'Thérapie par immersion',
            'Thérapie psycho-émotionnelle',
            'Thérapies brèves',
            'Thérapie systémique',
            'Thérapie troubles anxieux',
            'Thrombose veineuse',
            'Traitement de la BPCO (bronchopneumopathie chronique obstructive)',
            'Traitement de la bronchiolite',
            'Traitement de la mucoviscidose de l\'enfant',
            'Traitement de l\'asthme de l\'enfant',
            'Traitement des cicatrices',
            'Traitement des troubles de l\'équilibre',
            'Traitement par ultrasons',
            'Transplantation rénale',
            'Traumatologie',
            'Traumatologie du sport',
            'Traumatologie pédiatrique',
            'Taumatologue',
            'Tricopigmentation',
            'Trouble bipolaire',
            'Trouble du spectre de l\'autisme (TSA)',
            'Troubles de la mémoire',
            'Troubles digestifs',
            'Troubles du comportement alimentaire',
            'Troubles du sommeil',
            'Troubles neurologiques',
            'Tumeur cérébrale',
            'Tympanoplastie',
            'Ulcère',
            'Urologue',
            'Urticaire',
            'Uvéite',
            'Vaccination antigrippale',
            'Vaccination DTP',
            'Vaccination DTPC (Diphtérie Tétanos Poliomyélite Coqueluche)',
            'Vaccination Hépatite A',
            'Vaccination Hépatite B',
            'Vaccination Hépatites A et B',
            'Vaccination (hors COVID-19)',
            'Vaccination HPV (Papillomavirus)',
            'Vaccination Méningite',
            'Vaccination Pneumocoque',
            'Vaccination Rage',
            'Vaccination variole du singe',
            'Vaccin BCG',
            'Vaccin contre la fièvre jaune',
            'Vaginoplastie (lifting vaginal)',
            'Valvulopathie',
            'Varicelle',
            'Varices',
            'Varicocèle',
            'Varicosités',
            'Vasectomie',
            'Vénérologue',
            'Verres',
            'Verres progressifs',
            'Verrue',
            'Vertébroplastie',
            'Vertébrothérapie',
            'Verticalisateur',
            'Vertiges',
            'Victimologue',
            'Vidéocapsule de l\'intestin grêle',
            'VIH',
            'Viscosupplémentation',
            'Visite médicale d\'aptitude',
            'Vitiligo',
            'Vitrectomie',
            'Zona',
                    ];

             for ($i=0; $i < sizeof($expertises) ; $i++) { 

            $expert = new EntityExpertises();

            $expert->setExpertiseLabel($expertises[$i]);
            $manager->persist($expert);

            $manager->flush();
            # code...
        }

    }
}
