<?php

namespace App\DataFixtures;

use App\Entity\Specialities;
use Doctrine\Persistence\ObjectManager;
use Doctrine\Bundle\FixturesBundle\Fixture;

class SpecialitiesFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $spécialities = [
            'Chirurgien-dentiste',
            'Médecin généraliste',
            'Pédiatre',
            'Gynécologue médical et obstétrique',
            'Ophtalmologue',
            'Dermatologue et vénérologue',
            'Ostéopathe',
            'Masseur-kinésithérapeute',
            'Opticien-lunetier',
            'Pédicure-podologue',
            'Sage-femme',
            'ORL',
            'Allergologue',
            'Chirurgien urologue',
            'Rhumatologue',
            'Stomatologue',
            'Endocrinologue',
            'Chirurgien orthopédiste',
            'Diététicien',
            'Psychologue',
            'Neurologue',
            'Psychiatre',
            'Radiologue',
            'Cardiologue',
            'Gastro-entérologue et hépatologue',
            'Acupuncteur',
            'Addictologue',
            'Adjoint chirurgien-dentiste',
            'Adjoint médecin',
            'Anatomo-cyto-pathologiste',
            'Andrologue',
            'Anesthésiste',
            'Angiologue',
            'Assistant de service social',
            'Audioprothésiste',
            'Auxiliaire de puériculture',
            'Biologiste des agents infectieux',
            'Cancérologue',
            'Cancérologue biologiste',
            'Cancérologue médical',
            'Cancérologue radiothérapeute',
            'Chercheur médical',
            'Chiropracteur',
            'Chirurgien cancérologue',
            'Chirurgien de la face et du cou',
            'Chirurgien de la main',
            'Chirurgien endocrinien',
            'Chirurgien général',
            'Chirurgien infantile',
            'Chirurgien maxillo-facial',
            'Chirurgien maxillo-facial et stomatologue',
            'Chirurgien oral',
            'Chirurgien plasticien et esthétique',
            'Chirurgien thoracique et cardio-vasculaire',
            'Chirurgien vasculaire',
            'Chirurgien viscéral et digestif',
            'Cytogénéticien',
            'Dermatopathologue',
            'Échographiste',
            'Endocrinologue diabétologue',
            'Épithésiste',
            'Ergothérapeute',
            'Généticien',
            'Gériatre',
            'Gynécologue médical',
            'Gynécologue obstétricien',
            'Hématologue',
            'Hématologue biologiste',
            'Homéopathe',
            'Hydrologue',
            'Immunologue',
            'Infectiologue',
            'Infirmier',
            'Infirmier en pratique avancée',
            'Infirmière puéricultrice',
            'Manipulateur en électroradiologie médicale',
            'Médecin biologiste',
            'Médecin bucco-dentaire',
            'Médecin de la douleur',
            'Médecin de la reproduction',
            'Médecin de la reproduction et gynécologue médical',
            'Médecin de soins palliatifs',
            'Médecin du sport',
            'Médecin du travail',
            'Médecin morphologue et anti-âge',
            'Médecin nucléaire',
            'Médecin nutritionniste',
            'Médecin pénitentiaire',
            'Médecin réanimateur',
            'Médecin spécialiste de santé publique',
            'Médecin urgentiste',
            'Médecin vasculaire',
            'Néonatologue',
            'Néphrologue',
            'Neurochirurgien',
            'Neuro-pathologiste',
            'Neuro-psychiatre',
            'Oculariste',
            'Onco-hématologue',
            'Oncologue médical',
            'Onco-radiothérapeute',
            'ORL - Chirurgien de la face et du cou',
            'Orthodontiste',
            'Orthopédiste-orthésiste',
            'Orthophoniste',
            'Orthoprothésiste',
            'Orthoptiste',
            'Pathologies professionnelles et environnementales',
            'Pharmacien',
            'Pharmacologue',
            'Phlébologue',
            'Phoniatre',
            'Pneumologue',
            'Podologue pédiatrique',
            'Podo-orthésiste',
            'Psychiatre de l\'enfant et de l\'adolescent',
            'Psychomotricien',
            'Psychothérapeute',
            'Radiothérapeute',
            'Sage-femme échographiste',
            'Spécialiste en hémobiologie-transfusion',
            'Spécialiste en médecine aérospatiale',
            'Spécialiste en médecine de catastrophe',
            'Spécialiste en médecine interne',
            'Spécialiste en médecine légale et expertises médicales',
            'Spécialiste en médecine physique et de réadaptation',
            'Spécialiste en réanimation',
            'Technicien de biologie médicale',
            'Thermaliste',
            'Toxicologue',
            'Troubles de l\'Oralité Alimentaire (TOA)',
            'Végétalisme'
            ];

        for ($i=0; $i < sizeof($spécialities) ; $i++) { 

            $speciality = new Specialities();

            $speciality->setSpecialityLabel($spécialities[$i]);
            $manager->persist($speciality);
        }
        
        $manager->flush();
    }

    }

