<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUZoBewN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUZoBewN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUZoBewN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUZoBewN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUZoBewN\App_KernelDevDebugContainer([
    'container.build_hash' => 'UZoBewN',
    'container.build_id' => 'c09fd6c9',
    'container.build_time' => 1680857975,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUZoBewN');
