<?php

namespace ContainerUZoBewN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KYtLBiVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kYtLBiV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kYtLBiV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'aviaRepo' => ['privates', 'App\\Repository\\AviabilityRepository', 'getAviabilityRepositoryService', true],
        ], [
            'aviaRepo' => 'App\\Repository\\AviabilityRepository',
        ]);
    }
}
