<?php

namespace ContainerUZoBewN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U8F5_EiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u8F5.Ei' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u8F5.Ei'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appRepo' => ['privates', 'App\\Repository\\AppointmentRepository', 'getAppointmentRepositoryService', true],
            'patientRepo' => ['privates', 'App\\Repository\\PatientsRepository', 'getPatientsRepositoryService', true],
        ], [
            'appRepo' => 'App\\Repository\\AppointmentRepository',
            'patientRepo' => 'App\\Repository\\PatientsRepository',
        ]);
    }
}
