<?php

namespace ContainerUZoBewN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PoE4ZlAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PoE4ZlA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PoE4ZlA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appRepo' => ['privates', 'App\\Repository\\AppointmentRepository', 'getAppointmentRepositoryService', true],
            'proRepo' => ['privates', 'App\\Repository\\ProfessionnalsRepository', 'getProfessionnalsRepositoryService', true],
            'speRepo' => ['privates', 'App\\Repository\\SpecialitiesRepository', 'getSpecialitiesRepositoryService', true],
        ], [
            'appRepo' => 'App\\Repository\\AppointmentRepository',
            'proRepo' => 'App\\Repository\\ProfessionnalsRepository',
            'speRepo' => 'App\\Repository\\SpecialitiesRepository',
        ]);
    }
}
