<?php

namespace ContainerUZoBewN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LNIdVCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l_NIdVC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l_NIdVC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'patientUser' => ['privates', 'App\\Repository\\PatientsRepository', 'getPatientsRepositoryService', true],
            'proUser' => ['privates', 'App\\Repository\\ProfessionnalsRepository', 'getProfessionnalsRepositoryService', true],
            'tGI' => ['privates', 'security.csrf.token_generator', 'getSecurity_Csrf_TokenGeneratorService', true],
        ], [
            'mailer' => '?',
            'manager' => '?',
            'patientUser' => 'App\\Repository\\PatientsRepository',
            'proUser' => 'App\\Repository\\ProfessionnalsRepository',
            'tGI' => '?',
        ]);
    }
}
