<?php

namespace ContainerUZoBewN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E8t0sD3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e8t0sD3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e8t0sD3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appRepo' => ['privates', 'App\\Repository\\AppointmentRepository', 'getAppointmentRepositoryService', true],
            'aviaRepo' => ['privates', 'App\\Repository\\AviabilityRepository', 'getAviabilityRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'appRepo' => 'App\\Repository\\AppointmentRepository',
            'aviaRepo' => 'App\\Repository\\AviabilityRepository',
            'manager' => '?',
        ]);
    }
}
