<?php

namespace ContainerUZoBewN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ISGqTJvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iSGqTJv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iSGqTJv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'patients' => ['privates', 'App\\Repository\\PatientsRepository', 'getPatientsRepositoryService', true],
        ], [
            'patients' => 'App\\Repository\\PatientsRepository',
        ]);
    }
}
