<?php

namespace ContainerUZoBewN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4QesXKKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4QesXKK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4QesXKK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appointment' => ['privates', '.errored..service_locator.4QesXKK.App\\Entity\\Appointment', NULL, 'Cannot autowire service ".service_locator.4QesXKK": it needs an instance of "App\\Entity\\Appointment" but this type has been excluded in "config/services.yaml".'],
            'appointmentRepository' => ['privates', 'App\\Repository\\AppointmentRepository', 'getAppointmentRepositoryService', true],
        ], [
            'appointment' => 'App\\Entity\\Appointment',
            'appointmentRepository' => 'App\\Repository\\AppointmentRepository',
        ]);
    }
}
